export interface Country {
  name: string;
  capital: string;
}

export interface CountriesConfig {
  africa: Country[];
  asia: Country[];
  europe: Country[];
  north_america: Country[];
  south_america: Country[];
  australia_oceania: Country[];
}

export const countries: CountriesConfig = {
  africa: [
    { name: 'Egipto', capital: 'El Cairo' },
    { name: 'Nigeria', capital: 'Abuya' },
    { name: 'Kenia', capital: 'Nairobi' },
    { name: 'Sudáfrica', capital: 'Ciudad del Cabo' },
    { name: 'Marruecos', capital: 'Rabat' },
    { name: 'Etiopía', capital: 'Adís Abeba' },
    { name: 'Argelia', capital: 'Argel' },
    { name: 'Ghana', capital: 'Acra' },
    { name: 'Túnez', capital: 'Túnez' },
    { name: 'Costa de Marfil', capital: 'Yamusukro' },
    { name: 'Tanzania', capital: 'Dodoma' },
    { name: 'Camerún', capital: 'Yaundé' },
    { name: 'Madagascar', capital: 'Antananarivo' },
    { name: 'Senegal', capital: 'Dakar' },
    { name: 'Uganda', capital: 'Kampala' },
    { name: 'Sudán', capital: 'Jartum' },
    { name: 'Zambia', capital: 'Lusaka' },
    { name: 'Zimbabue', capital: 'Harare' },
    { name: 'Mozambique', capital: 'Maputo' },
    { name: 'Botsuana', capital: 'Gaborone' },
    { name: 'Malí', capital: 'Bamako' },
    { name: 'Níger', capital: 'Niamey' },
    { name: 'Burkina Faso', capital: 'Uagadugú' },
    { name: 'Angola', capital: 'Luanda' },
    { name: 'Ruanda', capital: 'Kigali' },
    { name: 'Benín', capital: 'Porto-Novo' },
    { name: 'Chad', capital: 'Yamena' },
    { name: 'República Democrática del Congo', capital: 'Kinshasa' },
    { name: 'República del Congo', capital: 'Brazzaville' },
    { name: 'Gabón', capital: 'Libreville' },
  ],
  asia: [
    { name: 'Japón', capital: 'Tokio' },
    { name: 'China', capital: 'Pekín' },
    { name: 'India', capital: 'Nueva Delhi' },
    { name: 'Corea del Sur', capital: 'Seúl' },
    { name: 'Indonesia', capital: 'Yakarta' },
    { name: 'Tailandia', capital: 'Bangkok' },
    { name: 'Vietnam', capital: 'Hanói' },
    { name: 'Malasia', capital: 'Kuala Lumpur' },
    { name: 'Filipinas', capital: 'Manila' },
    { name: 'Singapur', capital: 'Singapur' },
    { name: 'Emiratos Árabes Unidos', capital: 'Abu Dabi' },
    { name: 'Arabia Saudita', capital: 'Riad' },
    { name: 'Turquía', capital: 'Ankara' },
    { name: 'Kazajistán', capital: 'Astaná' },
    { name: 'Pakistán', capital: 'Islamabad' },
    { name: 'Irán', capital: 'Teherán' },
    { name: 'Israel', capital: 'Jerusalén' },
    { name: 'Qatar', capital: 'Doha' },
    { name: 'Corea del Norte', capital: 'Pionyang' },
    { name: 'Sri Lanka', capital: 'Sri Jayawardenapura Kotte' },
    { name: 'Nepal', capital: 'Katmandú' },
    { name: 'Bangladés', capital: 'Daca' },
    { name: 'Mongolia', capital: 'Ulán Bator' },
    { name: 'Camboya', capital: 'Nom Pen' },
    { name: 'Laos', capital: 'Vientián' },
    { name: 'Myanmar', capital: 'Naipyidó' },
    { name: 'Jordania', capital: 'Amán' },
    { name: 'Líbano', capital: 'Beirut' },
    { name: 'Siria', capital: 'Damasco' },
    { name: 'Omán', capital: 'Mascate' },
  ],
  europe: [
    { name: 'Albania', capital: 'Tirana' },
    { name: 'Alemania', capital: 'Berlín' },
    { name: 'Andorra', capital: 'Andorra la Vieja' },
    { name: 'Armenia', capital: 'Ereván' },
    { name: 'Austria', capital: 'Viena' },
    { name: 'Azerbaiyán', capital: 'Bakú' },
    { name: 'Bélgica', capital: 'Bruselas' },
    { name: 'Bielorrusia', capital: 'Minsk' },
    { name: 'Bosnia y Herzegovina', capital: 'Sarajevo' },
    { name: 'Bulgaria', capital: 'Sofía' },
    { name: 'Chipre', capital: 'Nicosia' },
    { name: 'Croacia', capital: 'Zagreb' },
    { name: 'Dinamarca', capital: 'Copenhague' },
    { name: 'Eslovaquia', capital: 'Bratislava' },
    { name: 'Eslovenia', capital: 'Liubliana' },
    { name: 'España', capital: 'Madrid' },
    { name: 'Estonia', capital: 'Tallin' },
    { name: 'Finlandia', capital: 'Helsinki' },
    { name: 'Francia', capital: 'París' },
    { name: 'Georgia', capital: 'Tiflis' },
    { name: 'Grecia', capital: 'Atenas' },
    { name: 'Hungría', capital: 'Budapest' },
    { name: 'Irlanda', capital: 'Dublín' },
    { name: 'Islandia', capital: 'Reikiavik' },
    { name: 'Italia', capital: 'Roma' },
    { name: 'Kazajistán', capital: 'Astaná' },
    { name: 'Kosovo', capital: 'Pristina' },
    { name: 'Letonia', capital: 'Riga' },
    { name: 'Liechtenstein', capital: 'Vaduz' },
    { name: 'Lituania', capital: 'Vilna' },
    { name: 'Luxemburgo', capital: 'Luxemburgo' },
    { name: 'Macedonia del Norte', capital: 'Skopie' },
    { name: 'Malta', capital: 'La Valeta' },
    { name: 'Moldavia', capital: 'Chisináu' },
    { name: 'Mónaco', capital: 'Mónaco' },
    { name: 'Montenegro', capital: 'Podgorica' },
    { name: 'Noruega', capital: 'Oslo' },
    { name: 'Países Bajos', capital: 'Ámsterdam' },
    { name: 'Polonia', capital: 'Varsovia' },
    { name: 'Portugal', capital: 'Lisboa' },
    { name: 'Reino Unido', capital: 'Londres' },
    { name: 'República Checa', capital: 'Praga' },
    { name: 'Rumanía', capital: 'Bucarest' },
    { name: 'Rusia', capital: 'Moscú' },
    { name: 'San Marino', capital: 'San Marino' },
    { name: 'Serbia', capital: 'Belgrado' },
    { name: 'Suecia', capital: 'Estocolmo' },
    { name: 'Suiza', capital: 'Berna' },
    { name: 'Turquía', capital: 'Ankara' },
    { name: 'Ucrania', capital: 'Kiev' },
    { name: 'Vaticano', capital: 'Ciudad del Vaticano' },
  ],
  north_america: [
    { name: 'Estados Unidos', capital: 'Washington D.C.' },
    { name: 'Canadá', capital: 'Ottawa' },
    { name: 'México', capital: 'Ciudad de México' },
    { name: 'Cuba', capital: 'La Habana' },
    { name: 'Jamaica', capital: 'Kingston' },
    { name: 'Haití', capital: 'Puerto Príncipe' },
    { name: 'Honduras', capital: 'Tegucigalpa' },
    { name: 'El Salvador', capital: 'San Salvador' },
    { name: 'Guatemala', capital: 'Ciudad de Guatemala' },
    { name: 'Costa Rica', capital: 'San José' },
    { name: 'Panamá', capital: 'Ciudad de Panamá' },
    { name: 'Nicaragua', capital: 'Managua' },
    { name: 'República Dominicana', capital: 'Santo Domingo' },
    { name: 'Puerto Rico', capital: 'San Juan' },
    { name: 'Bahamas', capital: 'Nasáu' },
    { name: 'Barbados', capital: 'Bridgetown' },
    { name: 'Belice', capital: 'Belmopán' },
    { name: 'Granada', capital: 'Saint George' },
    { name: 'San Vicente y las Granadinas', capital: 'Kingstown' },
    { name: 'Santa Lucía', capital: 'Castries' },
    { name: 'Antigua y Barbuda', capital: "Saint John's" },
    { name: 'Dominica', capital: 'Roseau' },
    { name: 'San Cristóbal y Nieves', capital: 'Basseterre' },
    { name: 'Trinidad y Tobago', capital: 'Puerto España' },
    { name: 'San Pedro y Miquelón', capital: 'Saint-Pierre' },
  ],
  south_america: [
    { name: 'Brasil', capital: 'Brasilia' },
    { name: 'Argentina', capital: 'Buenos Aires' },
    { name: 'Colombia', capital: 'Bogotá' },
    { name: 'Chile', capital: 'Santiago' },
    { name: 'Perú', capital: 'Lima' },
    { name: 'Venezuela', capital: 'Caracas' },
    { name: 'Ecuador', capital: 'Quito' },
    { name: 'Bolivia', capital: 'Sucre' },
    { name: 'Paraguay', capital: 'Asunción' },
    { name: 'Uruguay', capital: 'Montevideo' },
    { name: 'Surinam', capital: 'Paramaribo' },
    { name: 'Guyana', capital: 'Georgetown' },
    { name: 'Trinidad y Tobago', capital: 'Puerto España' },
    { name: 'Guayana Francesa', capital: 'Cayena' },
    { name: 'Islas Malvinas', capital: 'Stanley' },
    { name: 'Aruba', capital: 'Oranjestad' },
    { name: 'Curazao', capital: 'Willemstad' },
    { name: 'Bonaire', capital: 'Kralendijk' },
    { name: 'San Bartolomé', capital: 'Gustavia' },
    { name: 'San Eustaquio', capital: 'Oranjestad' },
    { name: 'San Martín', capital: 'Marigot' },
  ],
  australia_oceania: [
    { name: 'Australia', capital: 'Canberra' },
    { name: 'Nueva Zelanda', capital: 'Wellington' },
    { name: 'Fiyi', capital: 'Suva' },
    { name: 'Samoa', capital: 'Apia' },
    { name: 'Tonga', capital: 'Nukualofa' },
    { name: 'Vanuatu', capital: 'Port Vila' },
    { name: 'Papúa Nueva Guinea', capital: 'Puerto Moresby' },
    { name: 'Islas Salomón', capital: 'Honiara' },
    { name: 'Nauru', capital: 'Yaren' },
    { name: 'Kiribati', capital: 'Tarawa' },
    { name: 'Micronesia', capital: 'Palikir' },
    { name: 'Islas Marshall', capital: 'Majuro' },
    { name: 'Palaos', capital: 'Ngerulmud' },
    { name: 'Tuvalu', capital: 'Funafuti' },
    { name: 'Niue', capital: 'Alofi' },
    { name: 'Tahití', capital: 'Papeete' },
    { name: 'Guam', capital: 'Hagåtña' },
    { name: 'Samoa Americana', capital: 'Pago Pago' },
    { name: 'Nueva Caledonia', capital: 'Numea' },
    { name: 'Islas Pitcairn', capital: 'Adamstown' },
    { name: 'Tokelau', capital: 'Fakaofo' },
    { name: 'Wallis y Futuna', capital: 'Mata-Utu' },
    { name: 'Islas Cocos', capital: 'West Island' },
    { name: 'Islas Norfolk', capital: 'Kingston' },
  ],
};

export const countryIsoMap: Record<string, string> = {
  // Europa
  Alemania: 'de',
  Francia: 'fr',
  'Reino Unido': 'gb',
  España: 'es',
  Italia: 'it',
  'Países Bajos': 'nl',
  Suecia: 'se',
  Suiza: 'ch',
  Polonia: 'pl',
  Grecia: 'gr',
  Noruega: 'no',
  Portugal: 'pt',
  Irlanda: 'ie',
  Bélgica: 'be',
  Austria: 'at',
  Albania: 'al',
  Andorra: 'ad',
  Armenia: 'am',
  Azerbaiyán: 'az',
  Bielorrusia: 'by',
  'Bosnia y Herzegovina': 'ba',
  Bulgaria: 'bg',
  Chipre: 'cy',
  Croacia: 'hr',
  Dinamarca: 'dk',
  Eslovaquia: 'sk',
  Eslovenia: 'si',
  Estonia: 'ee',
  Finlandia: 'fi',
  Georgia: 'ge',
  Hungría: 'hu',
  Islandia: 'is',
  Kosovo: 'xk',
  Letonia: 'lv',
  Liechtenstein: 'li',
  Lituania: 'lt',
  Luxemburgo: 'lu',
  'Macedonia del Norte': 'mk',
  Malta: 'mt',
  Moldavia: 'md',
  Mónaco: 'mc',
  Montenegro: 'me',
  'República Checa': 'cz',
  Rumanía: 'ro',
  Rusia: 'ru',
  'San Marino': 'sm',
  Serbia: 'rs',
  Turquía: 'tr',
  Ucrania: 'ua',
  Vaticano: 'va',

  // Asia
  Japón: 'jp',
  China: 'cn',
  India: 'in',
  'Corea del Sur': 'kr',
  Indonesia: 'id',
  Tailandia: 'th',
  Vietnam: 'vn',
  Malasia: 'my',
  Filipinas: 'ph',
  Singapur: 'sg',
  'Emiratos Árabes Unidos': 'ae',
  'Arabia Saudita': 'sa',
  Kazajistán: 'kz',
  Pakistán: 'pk',
  Irán: 'ir',
  Israel: 'il',
  Qatar: 'qa',
  'Corea del Norte': 'kp',
  'Sri Lanka': 'lk',
  Nepal: 'np',
  Bangladés: 'bd',
  Mongolia: 'mn',
  Camboya: 'kh',
  Laos: 'la',
  Myanmar: 'mm',
  Jordania: 'jo',
  Líbano: 'lb',
  Siria: 'sy',
  Omán: 'om',

  // África
  Egipto: 'eg',
  Nigeria: 'ng',
  Kenia: 'ke',
  Sudáfrica: 'za',
  Marruecos: 'ma',
  Etiopía: 'et',
  Argelia: 'dz',
  Ghana: 'gh',
  Túnez: 'tn',
  'Costa de Marfil': 'ci',
  Tanzania: 'tz',
  Camerún: 'cm',
  Madagascar: 'mg',
  Senegal: 'sn',
  Uganda: 'ug',
  Sudán: 'sd',
  Zambia: 'zm',
  Zimbabue: 'zw',
  Mozambique: 'mz',
  Botsuana: 'bw',
  Malí: 'ml',
  Níger: 'ne',
  'Burkina Faso': 'bf',
  Angola: 'ao',
  Ruanda: 'rw',
  Benín: 'bj',
  Chad: 'td',
  'República Democrática del Congo': 'cd',
  'República del Congo': 'cg',
  Gabón: 'ga',

  // América del Norte
  'Estados Unidos': 'us',
  Canadá: 'ca',
  México: 'mx',
  Cuba: 'cu',
  Jamaica: 'jm',
  Haití: 'ht',
  Honduras: 'hn',
  'El Salvador': 'sv',
  Guatemala: 'gt',
  'Costa Rica': 'cr',
  Panamá: 'pa',
  Nicaragua: 'ni',
  'República Dominicana': 'do',
  'Puerto Rico': 'pr',
  Bahamas: 'bs',
  Barbados: 'bb',
  Belice: 'bz',
  Granada: 'gd',
  'San Vicente y las Granadinas': 'vc',
  'Santa Lucía': 'lc',
  'Antigua y Barbuda': 'ag',
  Dominica: 'dm',
  'San Cristóbal y Nieves': 'kn',
  'Trinidad y Tobago': 'tt',

  // América del Sur
  Brasil: 'br',
  Argentina: 'ar',
  Colombia: 'co',
  Chile: 'cl',
  Perú: 'pe',
  Venezuela: 've',
  Ecuador: 'ec',
  Bolivia: 'bo',
  Paraguay: 'py',
  Uruguay: 'uy',
  Surinam: 'sr',
  Guyana: 'gy',
  'Guayana Francesa': 'gf',
  'Islas Malvinas': 'fk',

  // Oceanía
  Australia: 'au',
  'Nueva Zelanda': 'nz',
  Fiyi: 'fj',
  Samoa: 'ws',
  Tonga: 'to',
  Vanuatu: 'vu',
  'Papúa Nueva Guinea': 'pg',
  'Islas Salomón': 'sb',
  Nauru: 'nr',
  Kiribati: 'ki',
  Micronesia: 'fm',
  'Islas Marshall': 'mh',
  Palaos: 'pw',
  Tuvalu: 'tv',
  Niue: 'nu',
};
